#!/usr/bin/env ansible-playbook
---
- hosts: brickolage
  vars:
  # was `sudo: yes` but that's deprecated
  become: yes
  # `ansible all -m setup --tree /tmp/facts` to see what facts we get
  gather_facts: no
  handlers:
    - name: restart supervisor
      service: name=supervisor state=stopped
      notify: restart supervisor part2
    # We want to stop, then start supervisor to grab all new config changes and restart all services
    - name: restart supervisor part2
      service: name=supervisor state=started
    - name: restart fcserver
      supervisorctl: name=fcserver state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart dhcpcd
      service: name=dhcpcd state=restarted
    - name: reload wlan0
      command: ifdown wlan0
      notify: reload wlan0 part2
    - name: reload wlan0 part2
      command: ifup wlan0
    - name: restart hostapd
      service: name=hostapd state=restarted
    - name: restart dnsmasq
      service: name=dnsmasq state=restarted

  tasks:
    - name: update apt
      apt: update_cache=yes
    - name: apt install git
      apt: name=git
    - name: fadecandy from github
      git: repo=https://github.com/scanlime/fadecandy.git
           dest=/home/pi/fadecandy
    - name: brickolage from github
      git: repo=https://github.com/hobzcalvin/brickolage.git
           dest=/home/pi/brickolage
    - name: fcserver config file
      copy:
        src: fcserver_config_lc_grb.json
        dest: /home/pi/fcserver_config_lc_grb.json
      notify: restart fcserver
    - name: fcserver log dir
      file:
        dest: /var/log/fcserver
        state: directory
      notify: restart supervisor
           
    - name: apt install supervisor
      apt: name=supervisor
    - name: supervisor conf dir
      file:
        dest: /etc/supervisor
        state: directory
      notify: restart supervisor
    - name: supervisor conf file
      copy:
        src: supervisord.conf
        dest: /etc/supervisor/supervisord.conf
      notify: restart supervisor
    - name: Link Supervisord conf
      file:
        src: /etc/supervisor/supervisord.conf
        dest: /etc/supervisord.conf
        state: link
      notify: restart supervisor
    - name: supervisord running
      service:
        name: supervisor
        state: running
        enabled: yes

    - name: apt install nginx
      apt: name=nginx
    - name: nginx running
      service:
        name: nginx
        state: running
        enabled: yes
    - name: nginx server config
      copy:
        src: nginx-sites-default
        dest: /etc/nginx/sites-available/default
      notify: restart nginx
        
    - name: install wap stuff
      apt: name={{item}}
      with_items:
        - dnsmasq
        - hostapd
    - name: turn off wlan0 in dhcpcd
      copy:
        src: dhcpcd.conf
        dest: /etc/dhcpcd.conf
      notify: restart dhcpcd
    - name: configure static ip for wlan0
      copy:
        src: network-interfaces
        dest: /etc/network/interfaces
      notify: reload wlan0
    - name: hostapd config
      copy:
        src: hostapd.conf
        dest: /etc/hostapd/hostapd.conf
      notify: restart hostapd
    - name: hostapd daemon
      copy:
        src: default-hostapd
        dest: /etc/default/hostapd
      notify: restart hostapd
    - name: dnsmasq config
      copy:
        src: dnsmasq.conf
        dest: /etc/dnsmasq.conf
      notify: restart dnsmasq
